---

- hosts: cluster
  become: true
  become_method: sudo
  tasks:
    - name: Update & Upgrade system
      apt:
        update_cache: yes
        upgrade: yes
        autoremove: yes
    - name: Install awscli
      apt:
        name: awscli
        update_cache: yes
        
