---

- hosts: gateway
  become_method: sudo
  tasks:
    - name: Update & Upgrade system
      become: true
      apt:
        update_cache: yes
        upgrade: yes
        autoremove: yes
    - name: Install Python
      become: true
      apt:
        name: python3
        update_cache: yes
    - name: Install pip
      become: true
      apt:
        name: pip
        update_cache: yes
    - name: Install ansible
      pip:
        name: ansible
    - name: Install git
      become: true
      apt:
        name: git
        update_cache: yes
    - name: Install awscli
      become: true
      apt:
        name: awscli
        update_cache: yes
    # Configure awscli
    # - name: Configure awscli credentials
    #   shell: aws configure set aws_access_key_id {{ aws_access_key_id }} --profile {{ aws_profile }}
    # - name: Configure awscli credentials
    #   shell: aws configure set aws_secret_access_key {{ aws_secret_access_key }} --profile {{ aws_profile }}
    # - name: Configure awscli region
    #   shell: aws configure set default.region eu-west-1
    - name: add public keys to authorized_keys
      authorized_key:
        user: ubuntu
        key: "{{ lookup('file', item) }}"
      with_fileglob:
        - ./keys/*.pub
    - name: Download playbook from git
      git:
        repo: https://github.com/MayaProtect/ansible.git
        dest: /home/{{ ansible_user }}/ansible
        version: main
        force: yes
    - name: Copy inventory
      copy:
        src: ./inventory/hosts.ini
        dest: /home/{{ ansible_user }}/ansible/inventory/hosts.ini

    - name: Copy private key
      copy:
        src: ./keys/ssh_key
        dest: /home/{{ ansible_user }}/.ssh/id_rsa
        mode: 0400

    - name: set remote host no verification
      shell: export ANSIBLE_HOST_KEY_CHECKING=False

    - name: Run playbook Update
      shell: ansible-playbook -i /home/{{ ansible_user }}/ansible/inventory/hosts.ini /home/{{ ansible_user }}/ansible/01_update_all.yml
    - name: Run playbook Install
      shell: ansible-playbook -i /home/{{ ansible_user }}/ansible/inventory/hosts.ini /home/{{ ansible_user }}/ansible/02_k3s_install.yml
